### ISSUE TITLE
test for italian layout

### ISSUE THREAD

**Issue by giorgiobeggiora** [dail8859/SurroundSelection#1]
Hi, i don't know how to develop a plugin but i can help testing the Italian keyboard layout.

**Comment by dail8859** [comment]
You are certainly welcome to test it out. You can install it via the [releases page](https://github.com/dail8859/SurroundSelection/releases) or the plugin manager from within Notepad++.

If it works with your keyboard layout then great...if not then some modifications would need done to the plugin since it hooks the keyboard input, and it would require making sure it is catching the right keyboard inputs from they layout.

**Comment by giorgiobeggiora** [comment]
Sorry for the late response.

Actually, this is the situation of the italian keyboard when i press a key on selected text:

    key         ' outputs []
    key SHIFT + ' outputs []
    key SHIFT + 9 outputs ()
    key SHIFT + 0 outputs ()
    key         à outputs ''
    key SHIFT + à outputs ""

I went to http://keycode.info/ and i noted the key codes of the italian layout

            ALT GR + 186 ---> [
    SHIFT + ALT GR + 186 ---> {
            ALT GR + 187 ---> ]
    SHIFT + ALT GR + 187 ---> }
                     219 ---> '
    SHIFT +           50 ---> "
    SHIFT +           56 ---> (
    SHIFT +           57 ---> )

**Comment by dail8859** [comment]
@giorgiobeggiora I think a long term solution would be to use whatever Win32 API is available to handle various keyboard layouts...I have no clue how to do this at all yet. The info you provided will help with testing.

**Comment by giorgiobeggiora** [comment]
Thank you
