### ISSUE TITLE
SurroundSelection hijacks shortcut Ctrl+Shift+2 when <NUL>text is selected<NUL>

### ISSUE THREAD

**Issue by NeilS-Wpg** [dail8859/SurroundSelection#16]
When SurrSel is enabled, and text is selected, shortcut Ctrl+Shift+2 results in a SurrSel-like action where the text is surrounded by a pair of `NUL`:

![image](https://user-images.githubusercontent.com/62523825/221378472-78dab169-a0c3-4f61-8cce-94af3b8d81fd.png)

... rather than the default action of jumping to the previous instance of text with "Style 2".

Problem goes away when SurrSel is disabled.

If no text is selected, the shortcut does the expecting jumping.

```
Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Users\Guest!\Downloads\npp.8.4.9.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.2604
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NavigateTo (2.4.1)
    NppConverter (4.5)
    NppExec (0.8.2)
    NppExport (0.4)
    PythonScript (2)
    SurroundSelection (1.4.1)
    VisualStudioLineCopy (1.0.0.2)
    _CustomizeToolbar (5.3)
```

**Comment by rdipardo** [comment]
See if this patched build resolves the problem:

- [SurroundSelection-9d85fbf-x64.zip](https://github.com/dail8859/SurroundSelection/files/10832744/SurroundSelection-9d85fbf-x64.zip)
- [SurroundSelection-9d85fbf-x64.sha546sum.txt](https://github.com/dail8859/SurroundSelection/files/10832745/SurroundSelection-9d85fbf-x64.sha546sum.txt)

The root of the problem is this `for-each` loop:

https://github.com/dail8859/SurroundSelection/blob/dfb6805abcfbe246f792a6c53e72d0ccb048c305/src/Main.cpp#L79-L81

It iterates a C-style byte string, and the terminating `'\0'` is pushed onto the vector of default delimiters.

When <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>2</kbd> is pressed, the plugin checks every delimiter:

https://github.com/dail8859/SurroundSelection/blob/dfb6805abcfbe246f792a6c53e72d0ccb048c305/src/Main.cpp#L208-L223

The key combo has no assigned delimiter (more precisely, it's `'\0'`); but the current logic makes an accidental match with the "recognized" `'\0'` delimiter and inserts that.

**Comment by NeilS-Wpg** [comment]
Fix confirmed in 64-bit version. Will the 32-bit be forthcoming?

(Also, it's surprising bug was noticed after so many years, assuming the bug was longstanding.)

Edit: 32 bit release announced [here](https://community.notepad-plus-plus.org/post/84508), can be fetched [here](https://ci.appveyor.com/project/dail8859/surroundselection/builds/46370230/job/31drlq1oyh39t6sv/artifacts)
